name: Auto Fetch Deals

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update-deals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Check Secrets
        run: |
          if [ -z "${{ secrets.AMAZON_ACCESS_KEY }}" ]; then echo "ACCESS KEY IS MISSING"; else echo "ACCESS KEY FOUND"; fi
          if [ -z "${{ secrets.AMAZON_SECRET_KEY }}" ]; then echo "SECRET KEY IS MISSING"; else echo "SECRET KEY FOUND"; fi
          if [ -z "${{ secrets.AMAZON_PARTNER_TAG }}" ]; then echo "PARTNER TAG IS MISSING"; else echo "PARTNER TAG FOUND"; fi

      - name: Fetch new deals
        env:
          AMAZON_ACCESS_KEY: ${{ secrets.AMAZON_ACCESS_KEY }}
          AMAZON_SECRET_KEY: ${{ secrets.AMAZON_SECRET_KEY }}
          AMAZON_PARTNER_TAG: ${{ secrets.AMAZON_PARTNER_TAG }}
        run: npm run update-deals

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.js
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update deals via Amazon API" && git push)

